In [10]:
%tensorflow_version 2.x


import tensorflow as tf
import tensorflow_datasets as tfds
import tensorflow_hub as hub

In [6]:
tf.__version__

'2.6.0'

In [4]:
!pip install tensorflow --upgrade

In [12]:
tfds.list_builders()

['abstract_reasoning',
 'accentdb',
 'aeslc',
 'aflw2k3d',
 'ag_news_subset',
 'ai2_arc',
 'ai2_arc_with_ir',
 'amazon_us_reviews',
 'anli',
 'arc',
 'bair_robot_pushing_small',
 'bccd',
 'beans',
 'big_patent',
 'bigearthnet',
 'billsum',
 'binarized_mnist',
 'binary_alpha_digits',
 'blimp',
 'bool_q',
 'c4',
 'caltech101',
 'caltech_birds2010',
 'caltech_birds2011',
 'cars196',
 'cassava',
 'cats_vs_dogs',
 'celeb_a',
 'celeb_a_hq',
 'cfq',
 'chexpert',
 'cifar10',
 'cifar100',
 'cifar10_1',
 'cifar10_corrupted',
 'citrus_leaves',
 'cityscapes',
 'civil_comments',
 'clevr',
 'clic',
 'clinc_oos',
 'cmaterdb',
 'cnn_dailymail',
 'coco',
 'coco_captions',
 'coil100',
 'colorectal_histology',
 'colorectal_histology_large',
 'common_voice',
 'coqa',
 'cos_e',
 'cosmos_qa',
 'covid19sum',
 'crema_d',
 'curated_breast_imaging_ddsm',
 'cycle_gan',
 'deep_weeds',
 'definite_pronoun_resolution',
 'dementiabank',
 'diabetic_retinopathy_detection',
 'div2k',
 'dmlab',
 'downsampled_imagenet',
 

In [39]:
(train_data, validation_data, test_data) = tfds.load(
'imdb_reviews',
split=['train[:80%]', 'train[80%:90%]', 'train[90%:]'],
as_supervised=True,)

In [40]:
type(train_data)

tensorflow.python.data.ops.dataset_ops.PrefetchDataset

In [41]:
train_data.batch(10)

<BatchDataset shapes: ((None,), (None,)), types: (tf.string, tf.int64)>

In [42]:
train_examples_batch, train_labels_batch = next(iter(train_data.batch(10)))
train_examples_batch

<tf.Tensor: shape=(10,), dtype=string, numpy=
array([b"This was an absolutely terrible movie. Don't be lured in by Christopher Walken or Michael Ironside. Both are great actors, but this must simply be their worst role in history. Even their great acting could not redeem this movie's ridiculous storyline. This movie is an early nineties US propaganda piece. The most pathetic scenes were those when the Columbian rebels were making their cases for revolutions. Maria Conchita Alonso appeared phony, and her pseudo-love affair with Walken was nothing but a pathetic emotional plug in a movie that was devoid of any real meaning. I am disappointed that there are movies like this, ruining actor's like Christopher Walken's good name. I could barely sit through it.",
       b'I have been known to fall asleep during films, but this is usually due to a combination of things including, really tired, being warm and comfortable on the sette and having just eaten a lot. However on this occasion I fell 

In [43]:
train_labels_batch

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([0, 0, 0, 1, 1, 1, 0, 0, 0, 0])>

In [45]:
pretrained_model = "https://tfhub.dev/google/tf2-preview/nnlm-de-dim50-with-normalization/1"
hub_layer = hub.KerasLayer(pretrained_model, input_shape=[], dtype=tf.string, trainable=True)

In [46]:
hub_layer(train_examples_batch[:2])

<tf.Tensor: shape=(2, 50), dtype=float32, numpy=
array([[-0.3162865 ,  0.9963474 ,  0.05003111,  1.8050171 ,  0.52256066,
        -0.07529207,  0.15048726,  0.0990252 ,  0.63166004,  0.5118274 ,
         0.00839786, -1.2807381 ,  0.47110453,  0.86252403, -0.25908616,
        -0.35625768, -0.8917568 , -1.0687852 , -0.2265635 ,  0.91594064,
        -0.75876766, -0.56161284,  0.4228015 ,  0.33008984,  0.9682548 ,
        -0.53217024, -0.3509205 ,  0.18059014, -0.7133345 , -0.09324868,
         0.15129805, -1.1266891 ,  0.958778  , -0.10324974,  0.04973495,
        -0.6242521 ,  1.3108275 ,  0.65257144,  0.5499875 ,  1.411971  ,
         0.09234099,  1.0040766 , -0.11369457, -0.7595081 , -1.1292775 ,
         0.4165966 , -0.83573574,  0.34312278, -0.5609723 , -1.6865692 ],
       [-0.4858114 ,  0.91723114,  0.19890271,  1.8544009 ,  0.44613925,
        -0.07693552,  0.15074152,  0.09643145,  0.7342921 ,  0.8408482 ,
         0.03438618, -1.3613851 ,  0.8463198 ,  1.2557055 , -0.19704835,
 

In [48]:
train_examples_batch[:2]

<tf.Tensor: shape=(2,), dtype=string, numpy=
array([b"This was an absolutely terrible movie. Don't be lured in by Christopher Walken or Michael Ironside. Both are great actors, but this must simply be their worst role in history. Even their great acting could not redeem this movie's ridiculous storyline. This movie is an early nineties US propaganda piece. The most pathetic scenes were those when the Columbian rebels were making their cases for revolutions. Maria Conchita Alonso appeared phony, and her pseudo-love affair with Walken was nothing but a pathetic emotional plug in a movie that was devoid of any real meaning. I am disappointed that there are movies like this, ruining actor's like Christopher Walken's good name. I could barely sit through it.",
       b'I have been known to fall asleep during films, but this is usually due to a combination of things including, really tired, being warm and comfortable on the sette and having just eaten a lot. However on this occasion I fell a

This is embedding layer to convert vector of two reviwes. Thats shown above.

Neural Network for our problem. The code given below.


In [49]:
model = tf.keras.Sequential()
model.add(hub_layer)
model.add(tf.keras.layers.Dense(16,activation="relu"))
model.add(tf.keras.layers.Dense(1,activation="sigmoid"))
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
keras_layer (KerasLayer)     (None, 50)                48948250  
_________________________________________________________________
dense (Dense)                (None, 16)                816       
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 17        
Total params: 48,949,083
Trainable params: 48,949,083
Non-trainable params: 0
_________________________________________________________________


In [58]:
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

In [59]:
model.fit(train_data.shuffle(10000).batch(512),
          epochs=20,
          validation_data=validation_data.batch(512),
          verbose=1)

Epoch 1/20
40/40 [==============================] - 26s 604ms/step - loss: 0.6787 - accuracy: 0.6174 - val_loss: 0.6273 - val_accuracy: 0.7872
Epoch 2/20
40/40 [==============================] - 24s 590ms/step - loss: 0.5738 - accuracy: 0.8076 - val_loss: 0.5150 - val_accuracy: 0.8196
Epoch 3/20
40/40 [==============================] - 24s 589ms/step - loss: 0.4418 - accuracy: 0.8523 - val_loss: 0.3997 - val_accuracy: 0.8516
Epoch 4/20
40/40 [==============================] - 24s 585ms/step - loss: 0.3263 - accuracy: 0.8897 - val_loss: 0.3274 - val_accuracy: 0.8768
Epoch 5/20
40/40 [==============================] - 24s 595ms/step - loss: 0.2489 - accuracy: 0.9135 - val_loss: 0.2934 - val_accuracy: 0.8808
Epoch 6/20
40/40 [==============================] - 24s 592ms/step - loss: 0.1982 - accuracy: 0.9343 - val_loss: 0.2822 - val_accuracy: 0.8832
Epoch 7/20
40/40 [==============================] - 24s 594ms/step - loss: 0.1632 - accuracy: 0.9464 - val_loss: 0.2753 - val_accuracy: 0.8892

In [60]:
model.predict(["This is worst movie i ever seen"])

array([[0.01074576]], dtype=float32)

In [62]:
model.predict(["This is the excellent movie dude"])

array([[0.9569799]], dtype=float32)

In [68]:
model.predict(["Good Movie"])

array([[0.48875496]], dtype=float32)

In [67]:
model.predict(["Bad Movie"])

array([[0.00205502]], dtype=float32)

In [70]:
model.predict(["Good feel movie","No story"])

array([[0.83235455],
       [0.01724741]], dtype=float32)

In [71]:
results = model.evaluate(test_data.batch(512), verbose=2)

for name, value in zip(model.metrics_names, results):
  print("%s: %.3f" % (name, value))

5/5 - 1s - loss: 0.3303 - accuracy: 0.8928
loss: 0.330
accuracy: 0.893
